language: csharp
solution: net/simon-speck-net.sln

matrix:
  include:
    - os: osx
    - os: linux
      sudo: yes
      dist: trusty

git:
    submodules: false

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}
  - pushd ${DEPS_DIR}
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Darwin-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/CMake.app/Contents/bin:${PATH}
    fi
  - cmake --version
  - popd

before_script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    else
      sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    fi
  - git submodule update --init --recursive

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./scripts/plugins/deploy_linux.sh
      ./scripts/build.sh
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./scripts/plugins/deploy_mac.sh
      ./scripts/build.sh
    fi

